### ISSUE TITLE
更新すると Version が null になる

### ISSUE THREAD

**Issue by fukasawa-t** [Naoya-Horiguchi/redmine_tools#33]
履歴には「対象バージョン を ** にセット」と表示されるが、セットできていない。

**Comment by Naoya-Horiguchi** [comment]
b68a31e1ec5f37f089176cfc8563c9f421bd459d で修正済みなので、バージョンを更新してみてください。

**Comment by fukasawa-t** [comment]
ありがとうございます。修正されていることを確認しました。
